name: drl_bess
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11.14
  - jupyterlab=4.4.7
  - numpy=2.3.1
  - pandas=2.3.3
  - matplotlib=3.10.6
  - scipy=1.16.0
  - scikit-learn=1.7.1
  - gymnasium=0.28.1
  - stable-baselines3=2.3.2
  - pandapower=2.14.7
  - protobuf=3.20.3
  - tensorboard=2.19.0
  - tqdm=4.67.1
  - rich=14.2.0
  - ipywidgets=8.1.7
  - pip
  - pip:
      - torch==2.6.0
      - sb3-contrib==2.7.1